import { test, expect } from '@playwright/test'

test.describe('Overview Page', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/')
  })

  test('loads and displays project name', async ({ page }) => {
    await expect(page.locator('h1')).toBeVisible()
    await expect(page.locator('h1')).toHaveText('jaffle_shop')
  })

  test('shows project totals as a summary line', async ({ page }) => {
    await expect(page.getByText(/\d+ models · \d+ sources · \d+ tests/)).toBeVisible()
  })

  test('leads with search', async ({ page }) => {
    const search = page.getByRole('searchbox', { name: 'Search this project' })
    await expect(search).toBeVisible()

    await search.fill('customers')
    const results = page.getByRole('list', { name: 'Search results' })
    await expect(results.getByRole('button').first()).toContainText(/customers/i)
  })

  test('search results navigate to the resource page', async ({ page }) => {
    await page.getByRole('searchbox', { name: 'Search this project' }).fill('customers')
    const results = page.getByRole('list', { name: 'Search results' })
    await results.getByRole('button').first().click()
    await expect(page).toHaveURL(/#\/(model|source)\//)
  })

  test('pressing Enter in search opens the full search page', async ({ page }) => {
    const search = page.getByRole('searchbox', { name: 'Search this project' })
    await search.fill('orders')
    await search.press('Enter')
    await expect(page).toHaveURL(/#\/search\?q=orders/)
  })

  test('shows the project map with layer counts', async ({ page }) => {
    const map = page.getByRole('region', { name: 'Project map' })
    await expect(map).toBeVisible()
    await expect(map.getByRole('button').first()).toContainText(/nodes?/)
  })

  test('clicking a layer reveals the models in it', async ({ page }) => {
    const map = page.getByRole('region', { name: 'Project map' })
    const segment = map.getByRole('button').first()
    await segment.click()
    await expect(segment).toHaveAttribute('aria-expanded', 'true')
  })

  test('shows starting points that open lineage pinned to the model', async ({ page }) => {
    const section = page.getByRole('region', { name: 'Start exploring' })
    await expect(section).toBeVisible()
    await section.getByRole('button').first().click()
    await expect(page).toHaveURL(/#\/lineage\?pins=/)
  })

  test('states health as outstanding work, not a letter grade', async ({ page }) => {
    const strip = page.getByRole('button', { name: /Project health/ })
    await expect(strip).toBeVisible()
    // The grade belongs on the Health page, where the reader opted into it.
    await expect(strip).not.toContainText('/100')
  })

  test('health strip navigates to the health page', async ({ page }) => {
    await page.getByRole('button', { name: /Project health/ }).click()
    await expect(page).toHaveURL(/#\/health/)
  })

  test('does not show a model table until a tag filter is applied', async ({ page }) => {
    await expect(page.locator('table')).toHaveCount(0)
  })

  test('displays docglow version info', async ({ page }) => {
    await expect(page.getByText(/Generated by docglow/)).toBeVisible()
  })
})
